import React, { useState, useCallback } from "react";
import { GATEWAY_API , apiFetch } from "@/lib/config";
import BuildStrategyDetector from "./BuildStrategyDetector";
import TriggerConfig from "./TriggerConfig";

type BuildStrategy = "auto" | "dockerfile" | "docker-compose" | "script";

interface EnvVar {
  key: string;
  value: string;
  secret: boolean;
}

interface Props {
  environments: { name: string; display_name: string }[];
  onBack: () => void;
  onDeployed?: () => void;
}

export default function QuickDeployForm({ environments, onBack, onDeployed }: Props) {
  // Repository
  const [repoUrl, setRepoUrl] = useState("");
  const [branch, setBranch] = useState("main");

  // Build
  const [strategy, setStrategy] = useState<BuildStrategy>("auto");
  const [buildCmd, setBuildCmd] = useState("");
  const [startCmd, setStartCmd] = useState("");

  // Target
  const [environment, setEnvironment] = useState(environments[0]?.name || "dev");
  const [port, setPort] = useState("3000");
  const [healthCheckPath, setHealthCheckPath] = useState("");

  // Env vars
  const [envVars, setEnvVars] = useState<EnvVar[]>([]);

  // Triggers
  const [triggers, setTriggers] = useState({
    webhookEnabled: true,
    branch: "main",
    tagPattern: "",
    cronSchedule: "",
    manualOnly: false,
  });

  // State
  const [deploying, setDeploying] = useState(false);
  const [msg, setMsg] = useState("");
  const [showYaml, setShowYaml] = useState(false);

  const handleDetected = useCallback((result: { suggested_build_cmd: string; suggested_start_cmd: string }) => {
    if (result.suggested_build_cmd && !buildCmd) setBuildCmd(result.suggested_build_cmd);
    if (result.suggested_start_cmd && !startCmd) setStartCmd(result.suggested_start_cmd);
  }, [buildCmd, startCmd]);

  const addEnvVar = () => setEnvVars([...envVars, { key: "", value: "", secret: false }]);

  const updateEnvVar = (index: number, patch: Partial<EnvVar>) => {
    const updated = [...envVars];
    updated[index] = { ...updated[index], ...patch };
    setEnvVars(updated);
  };

  const removeEnvVar = (index: number) => setEnvVars(envVars.filter((_, i) => i !== index));

  const buildPayload = () => ({
    repo_url: repoUrl,
    branch,
    build_strategy: strategy,
    build_cmd: buildCmd,
    start_cmd: startCmd,
    environment,
    port: parseInt(port, 10) || 3000,
    health_check_path: healthCheckPath || undefined,
    env_vars: Object.fromEntries(
      envVars.filter((v) => v.key).map((v) => [v.key, { value: v.value, secret: v.secret }])
    ),
    triggers: {
      push: triggers.webhookEnabled ? { branches: [triggers.branch || branch] } : undefined,
      tag: triggers.tagPattern ? { pattern: triggers.tagPattern } : undefined,
      cron: triggers.cronSchedule || undefined,
      manual: triggers.manualOnly || true,
    },
  });

  const generateYaml = () => {
    const p = buildPayload();
    const steps: string[] = [];

    // Build step
    if (strategy !== "script") {
      const image = strategy === "dockerfile" || strategy === "docker-compose" ? "docker" : "node:22";
      const cmd = p.build_cmd || "npm ci && npm run build";
      steps.push(`  - name: build\n    image: ${image}\n    commands:\n      - ${cmd}`);
    }

    // Deploy step
    const deployCmd = p.start_cmd || `docker run -d -p ${p.port}:${p.port} app:latest`;
    const secretKeys = envVars.filter((v) => v.secret && v.key).map((v) => v.key);
    let deployStep = `  - name: deploy\n    image: bond-deploy-agent\n    commands:\n      - ${deployCmd}\n    depends_on: [build]`;
    if (secretKeys.length > 0) {
      deployStep += `\n    secrets: [${secretKeys.join(", ")}]`;
    }
    steps.push(deployStep);

    // Health check
    if (p.health_check_path) {
      steps.push(`  - name: health-check\n    image: curlimages/curl\n    commands:\n      - sleep 5\n      - curl -f http://localhost:${p.port}${p.health_check_path} || exit 1\n    depends_on: [deploy]`);
    }

    // Trigger
    const onParts: string[] = [];
    if (p.triggers.push) onParts.push(`  push:\n    branches: [${p.triggers.push.branches.join(", ")}]`);
    if (p.triggers.tag) onParts.push(`  tag:\n    pattern: "${p.triggers.tag.pattern}"`);
    if (p.triggers.cron) onParts.push(`  cron: "${p.triggers.cron}"`);
    onParts.push(`  manual: true`);

    // Env vars (non-secret)
    const envLines = envVars
      .filter((v) => v.key && !v.secret)
      .map((v) => `  ${v.key}: "${v.value}"`);

    let yaml = `# .bond/deploy.yml\n# Auto-generated by Bond Quick Deploy\n\npipeline: quick-deploy\n\non:\n${onParts.join("\n")}\n\nsteps:\n${steps.join("\n\n")}\n\nenvironments:\n  - name: ${p.environment}\n    auto_promote: true\n`;

    if (secretKeys.length > 0) {
      yaml += `\nsecrets:\n${secretKeys.map((k) => `  ${k}:\n    source: environment`).join("\n")}\n`;
    }

    if (envLines.length > 0) {
      yaml += `\n# Non-secret environment variables\n# Set these in your environment or .env file:\n${envLines.map((l) => `#${l}`).join("\n")}\n`;
    }

    return yaml;
  };

  const handleDeploy = async () => {
    if (!repoUrl) {
      setMsg("Repository URL is required.");
      return;
    }
    setDeploying(true);
    setMsg("");
    try {
      const res = await apiFetch(`${GATEWAY_API}/deployments/quick-deploy`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(buildPayload()),
      });
      if (!res.ok) {
        if (res.status === 404) {
          setMsg("Quick Deploy API not available yet. Export the YAML and configure manually.");
        } else {
          const data = await res.json().catch(() => ({}));
          setMsg(data.error || data.detail || "Deployment failed.");
        }
      } else {
        setMsg("Deployment started successfully!");
        onDeployed?.();
      }
    } catch {
      setMsg("Could not reach deployment API. Export the YAML and configure manually.");
    } finally {
      setDeploying(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h2 style={styles.title}>Quick Deploy</h2>
        <button style={styles.secondaryButton} onClick={onBack}>Advanced ↓</button>
      </div>

      {/* Connect Repository */}
      <div style={styles.section}>
        <h3 style={styles.sectionTitle}>Connect Repository</h3>
        <div style={styles.fieldRow}>
          <div style={styles.fieldGrow}>
            <label style={styles.label}>Repository URL</label>
            <input
              style={styles.input}
              value={repoUrl}
              onChange={(e) => setRepoUrl(e.target.value)}
              placeholder="github.com/yourorg/yourapp"
            />
          </div>
        </div>
        <div style={styles.fieldRow}>
          <div style={styles.field}>
            <label style={styles.label}>Branch</label>
            <input
              style={styles.input}
              value={branch}
              onChange={(e) => setBranch(e.target.value)}
              placeholder="main"
            />
          </div>
        </div>
      </div>

      {/* Build */}
      <div style={styles.section}>
        <h3 style={styles.sectionTitle}>Build</h3>
        <div style={styles.label}>Strategy</div>
        <div style={styles.radioGroup}>
          {(["auto", "dockerfile", "docker-compose", "script"] as BuildStrategy[]).map((s) => (
            <label key={s} style={styles.radioLabel}>
              <input
                type="radio"
                name="strategy"
                checked={strategy === s}
                onChange={() => setStrategy(s)}
              />
              <span>{s === "auto" ? "Auto-detect" : s === "dockerfile" ? "Dockerfile" : s === "docker-compose" ? "Docker Compose" : "Script (custom)"}</span>
            </label>
          ))}
        </div>
        <BuildStrategyDetector
          repoUrl={repoUrl}
          strategy={strategy}
          onDetected={handleDetected}
        />
        <div style={styles.fieldRow}>
          <div style={styles.field}>
            <label style={styles.label}>Build command</label>
            <input
              style={styles.input}
              value={buildCmd}
              onChange={(e) => setBuildCmd(e.target.value)}
              placeholder="npm run build"
            />
          </div>
          <div style={styles.field}>
            <label style={styles.label}>Start command</label>
            <input
              style={styles.input}
              value={startCmd}
              onChange={(e) => setStartCmd(e.target.value)}
              placeholder="npm start"
            />
          </div>
        </div>
      </div>

      {/* Target */}
      <div style={styles.section}>
        <h3 style={styles.sectionTitle}>Target</h3>
        <div style={styles.fieldRow}>
          <div style={styles.field}>
            <label style={styles.label}>Environment</label>
            <select
              style={styles.select}
              value={environment}
              onChange={(e) => setEnvironment(e.target.value)}
            >
              {environments.map((env) => (
                <option key={env.name} value={env.name}>{env.display_name}</option>
              ))}
            </select>
            <div style={styles.hint}>Single environment — no promotion pipeline</div>
          </div>
          <div style={styles.field}>
            <label style={styles.label}>Port</label>
            <input
              style={{ ...styles.input, maxWidth: "100px" }}
              value={port}
              onChange={(e) => setPort(e.target.value)}
              placeholder="3000"
            />
          </div>
          <div style={styles.field}>
            <label style={styles.label}>Health check path</label>
            <input
              style={styles.input}
              value={healthCheckPath}
              onChange={(e) => setHealthCheckPath(e.target.value)}
              placeholder="/health (optional)"
            />
          </div>
        </div>
      </div>

      {/* Triggers */}
      <TriggerConfig settings={triggers} onChange={setTriggers} />

      {/* Environment Variables */}
      <div style={styles.section}>
        <h3 style={styles.sectionTitle}>Environment Variables</h3>
        {envVars.map((v, i) => (
          <div key={i} style={styles.envRow}>
            <input
              style={{ ...styles.input, flex: 1, minWidth: "120px" }}
              value={v.key}
              onChange={(e) => updateEnvVar(i, { key: e.target.value })}
              placeholder="KEY"
            />
            <input
              style={{ ...styles.input, flex: 2 }}
              value={v.value}
              onChange={(e) => updateEnvVar(i, { value: e.target.value })}
              placeholder="value"
              type={v.secret ? "password" : "text"}
            />
            <button
              style={{ ...styles.iconButton, color: v.secret ? "#6c8aff" : "#5a5a6e" }}
              onClick={() => updateEnvVar(i, { secret: !v.secret })}
              title={v.secret ? "Secret (encrypted)" : "Not secret"}
            >
              {v.secret ? "\u{1F512}" : "\u{1F513}"}
            </button>
            <button
              style={{ ...styles.iconButton, color: "#ff6c8a" }}
              onClick={() => removeEnvVar(i)}
              title="Remove"
            >
              ×
            </button>
          </div>
        ))}
        <button style={styles.addButton} onClick={addEnvVar}>+ Add Variable</button>
      </div>

      {/* Actions */}
      <div style={styles.actions}>
        <button
          style={{ ...styles.deployButton, opacity: deploying ? 0.5 : 1 }}
          onClick={handleDeploy}
          disabled={deploying}
        >
          {deploying ? "Deploying..." : "\u{1F680} Deploy"}
        </button>
        <button style={styles.secondaryButton} onClick={() => setShowYaml(!showYaml)}>
          {showYaml ? "Hide YAML" : "Export as .bond/deploy.yml"}
        </button>
      </div>

      {showYaml && (
        <div style={styles.yamlContainer}>
          <div style={styles.yamlHeader}>
            <span style={styles.yamlTitle}>.bond/deploy.yml</span>
            <button
              style={styles.copyButton}
              onClick={() => navigator.clipboard?.writeText(generateYaml())}
            >
              Copy
            </button>
          </div>
          <pre style={styles.yamlPre}>{generateYaml()}</pre>
          <div style={styles.hint}>
            Add this file to your repository to graduate to pipeline-as-code (Tier 2).
          </div>
        </div>
      )}

      {msg && (
        <div style={{
          fontSize: "0.85rem",
          color: msg.includes("success") ? "#6cffa0" : msg.includes("not available") || msg.includes("Could not") ? "#ffcc44" : "#ff6c8a",
        }}>
          {msg}
        </div>
      )}
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: { display: "flex", flexDirection: "column", gap: "16px" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  title: { fontSize: "1.1rem", fontWeight: 600, color: "#6c8aff", margin: 0 },
  section: {
    backgroundColor: "#12121a",
    borderRadius: "12px",
    padding: "16px",
    borderWidth: "1px", borderStyle: "solid", borderColor: "#1e1e2e",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  sectionTitle: { fontSize: "0.95rem", fontWeight: 600, color: "#e0e0e8", margin: 0 },
  fieldRow: { display: "flex", gap: "12px", flexWrap: "wrap" as const },
  field: { display: "flex", flexDirection: "column", gap: "4px", minWidth: "140px" },
  fieldGrow: { display: "flex", flexDirection: "column", gap: "4px", flex: 1, minWidth: "200px" },
  label: { fontSize: "0.8rem", color: "#8888a0" },
  input: {
    backgroundColor: "#1e1e2e",
    borderWidth: "1px", borderStyle: "solid", borderColor: "#2a2a3e",
    borderRadius: "8px",
    padding: "8px 10px",
    color: "#e0e0e8",
    fontSize: "0.85rem",
    outline: "none",
  },
  select: {
    backgroundColor: "#1e1e2e",
    borderWidth: "1px", borderStyle: "solid", borderColor: "#2a2a3e",
    borderRadius: "8px",
    padding: "8px 10px",
    color: "#e0e0e8",
    fontSize: "0.85rem",
    outline: "none",
  },
  hint: { fontSize: "0.72rem", color: "#5a5a6e" },
  radioGroup: { display: "flex", gap: "16px", flexWrap: "wrap" as const },
  radioLabel: { display: "flex", alignItems: "center", gap: "4px", fontSize: "0.85rem", color: "#e0e0e8", cursor: "pointer" },
  envRow: { display: "flex", gap: "8px", alignItems: "center" },
  iconButton: {
    backgroundColor: "transparent",
    borderWidth: 0, borderStyle: "none", borderColor: "transparent",
    fontSize: "1rem",
    cursor: "pointer",
    padding: "4px 6px",
  },
  addButton: {
    backgroundColor: "transparent",
    borderWidth: "1px", borderStyle: "dashed", borderColor: "#2a2a3e",
    borderRadius: "8px",
    padding: "8px 12px",
    color: "#6c8aff",
    fontSize: "0.82rem",
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  actions: { display: "flex", gap: "12px", alignItems: "center" },
  deployButton: {
    backgroundColor: "#6c8aff",
    color: "#fff",
    borderWidth: 0, borderStyle: "none", borderColor: "transparent",
    borderRadius: "8px",
    padding: "12px 24px",
    fontSize: "0.95rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  secondaryButton: {
    backgroundColor: "#2a2a3e",
    color: "#e0e0e8",
    borderWidth: "1px", borderStyle: "solid", borderColor: "#3a3a4e",
    borderRadius: "8px",
    padding: "8px 16px",
    fontSize: "0.85rem",
    cursor: "pointer",
  },
  yamlContainer: {
    backgroundColor: "#0a0a12",
    borderRadius: "12px",
    borderWidth: "1px", borderStyle: "solid", borderColor: "#1e1e2e",
    overflow: "hidden",
  },
  yamlHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 16px",
    backgroundColor: "#12121a",
    borderBottomWidth: "1px", borderBottomStyle: "solid", borderBottomColor: "#1e1e2e",
  },
  yamlTitle: { fontSize: "0.82rem", color: "#8888a0", fontFamily: "monospace" },
  copyButton: {
    backgroundColor: "#2a2a3e",
    color: "#6c8aff",
    borderWidth: 0, borderStyle: "none", borderColor: "transparent",
    borderRadius: "6px",
    padding: "4px 10px",
    fontSize: "0.78rem",
    cursor: "pointer",
  },
  yamlPre: {
    margin: 0,
    padding: "16px",
    color: "#e0e0e8",
    fontSize: "0.8rem",
    fontFamily: "monospace",
    whiteSpace: "pre-wrap" as const,
    overflowX: "auto" as const,
  },
};
