// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  agentId: __t.string().name("agent_id"),
  url: __t.string(),
  name: __t.string(),
  defaultBranch: __t.string().name("default_branch"),
  activeBranch: __t.string().name("active_branch"),
  credentialId: __t.string().name("credential_id"),
  lastSyncedAt: __t.u64().name("last_synced_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
