// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddAgentReducer from "./add_agent_reducer";
import AddAgentChannelReducer from "./add_agent_channel_reducer";
import AddAgentMountReducer from "./add_agent_mount_reducer";
import AddAgentPromptFragmentReducer from "./add_agent_prompt_fragment_reducer";
import AddConversationMessageReducer from "./add_conversation_message_reducer";
import AddMcpServerReducer from "./add_mcp_server_reducer";
import AddModelReducer from "./add_model_reducer";
import AddPromptFragmentReducer from "./add_prompt_fragment_reducer";
import AddPromptFragmentVersionReducer from "./add_prompt_fragment_version_reducer";
import AddPromptTemplateReducer from "./add_prompt_template_reducer";
import AddPromptTemplateVersionReducer from "./add_prompt_template_version_reducer";
import AddProviderReducer from "./add_provider_reducer";
import AddWorkItemReducer from "./add_work_item_reducer";
import AddComponentResourceReducer from "./add_component_resource_reducer";
import AddComponentScriptReducer from "./add_component_script_reducer";
import AddComponentSecretReducer from "./add_component_secret_reducer";
import AddDeploymentApproverReducer from "./add_deployment_approver_reducer";
import ConsumeSystemEventReducer from "./consume_system_event_reducer";
import CreateConversationReducer from "./create_conversation_reducer";
import CreateWorkPlanReducer from "./create_work_plan_reducer";
import CreateAlertRuleReducer from "./create_alert_rule_reducer";
import CreateComponentReducer from "./create_component_reducer";
import CreateDeploymentEnvironmentReducer from "./create_deployment_environment_reducer";
import CreateDeploymentResourceReducer from "./create_deployment_resource_reducer";
import CreateDeploymentTriggerReducer from "./create_deployment_trigger_reducer";
import CreateMonitoringAlertReducer from "./create_monitoring_alert_reducer";
import DeactivateComponentReducer from "./deactivate_component_reducer";
import DeleteAgentReducer from "./delete_agent_reducer";
import DeleteAgentChannelsForAgentReducer from "./delete_agent_channels_for_agent_reducer";
import DeleteAgentMountsForAgentReducer from "./delete_agent_mounts_for_agent_reducer";
import DeleteAgentPromptFragmentReducer from "./delete_agent_prompt_fragment_reducer";
import DeleteConversationReducer from "./delete_conversation_reducer";
import DeleteConversationMessageReducer from "./delete_conversation_message_reducer";
import DeleteMcpServerReducer from "./delete_mcp_server_reducer";
import DeletePromptFragmentReducer from "./delete_prompt_fragment_reducer";
import DeletePromptTemplateReducer from "./delete_prompt_template_reducer";
import DeleteProviderReducer from "./delete_provider_reducer";
import DeleteProviderAliasReducer from "./delete_provider_alias_reducer";
import DeleteProviderApiKeyReducer from "./delete_provider_api_key_reducer";
import DeleteSettingReducer from "./delete_setting_reducer";
import DeleteWorkPlanReducer from "./delete_work_plan_reducer";
import DeleteAlertRuleReducer from "./delete_alert_rule_reducer";
import DeleteDeploymentResourceReducer from "./delete_deployment_resource_reducer";
import DeleteDeploymentTriggerReducer from "./delete_deployment_trigger_reducer";
import DisableAlertRuleReducer from "./disable_alert_rule_reducer";
import EnableAlertRuleReducer from "./enable_alert_rule_reducer";
import EnqueueSystemEventReducer from "./enqueue_system_event_reducer";
import ImportConversationReducer from "./import_conversation_reducer";
import ImportConversationMessageReducer from "./import_conversation_message_reducer";
import ImportWorkItemReducer from "./import_work_item_reducer";
import ImportWorkPlanReducer from "./import_work_plan_reducer";
import InitiatePromotionReducer from "./initiate_promotion_reducer";
import LogToolReducer from "./log_tool_reducer";
import RecordApprovalReducer from "./record_approval_reducer";
import RemoveComponentResourceReducer from "./remove_component_resource_reducer";
import RemoveComponentScriptReducer from "./remove_component_script_reducer";
import RemoveComponentSecretReducer from "./remove_component_secret_reducer";
import RemoveDeploymentApproverReducer from "./remove_deployment_approver_reducer";
import RenameWorkItemReducer from "./rename_work_item_reducer";
import ResolveMonitoringAlertReducer from "./resolve_monitoring_alert_reducer";
import SaveMessageReducer from "./save_message_reducer";
import SetDefaultAgentReducer from "./set_default_agent_reducer";
import SetProviderAliasReducer from "./set_provider_alias_reducer";
import SetProviderApiKeyReducer from "./set_provider_api_key_reducer";
import SetSettingReducer from "./set_setting_reducer";
import UpdateAgentReducer from "./update_agent_reducer";
import UpdateConversationReducer from "./update_conversation_reducer";
import UpdateMcpServerReducer from "./update_mcp_server_reducer";
import UpdateProviderReducer from "./update_provider_reducer";
import UpdateWorkItemReducer from "./update_work_item_reducer";
import UpdateWorkPlanStatusReducer from "./update_work_plan_status_reducer";
import UpdateAlertRuleReducer from "./update_alert_rule_reducer";
import UpdateComponentReducer from "./update_component_reducer";
import UpdateDeploymentEnvironmentReducer from "./update_deployment_environment_reducer";
import UpdateDeploymentResourceReducer from "./update_deployment_resource_reducer";
import UpdateDeploymentTriggerReducer from "./update_deployment_trigger_reducer";
import UpdatePromotionStatusReducer from "./update_promotion_status_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentChannelsRow from "./agent_channels_table";
import AgentPromptFragmentsRow from "./agent_prompt_fragments_table";
import AgentWorkspaceMountsRow from "./agent_workspace_mounts_table";
import AgentsRow from "./agents_table";
import AlertRulesRow from "./alert_rules_table";
import AlertsRow from "./alerts_table";
import ApprovalsRow from "./approvals_table";
import ComponentResourcesRow from "./component_resources_table";
import ComponentScriptsRow from "./component_scripts_table";
import ComponentSecretsRow from "./component_secrets_table";
import ComponentsRow from "./components_table";
import ConversationMessagesRow from "./conversation_messages_table";
import ConversationsRow from "./conversations_table";
import EnvironmentApproversRow from "./environment_approvers_table";
import EnvironmentHistoryRow from "./environment_history_table";
import EnvironmentsRow from "./environments_table";
import LlmModelsRow from "./llm_models_table";
import McpServersRow from "./mcp_servers_table";
import MessagesRow from "./messages_table";
import PromotionsRow from "./promotions_table";
import PromptFragmentVersionsRow from "./prompt_fragment_versions_table";
import PromptFragmentsRow from "./prompt_fragments_table";
import PromptTemplateVersionsRow from "./prompt_template_versions_table";
import PromptTemplatesRow from "./prompt_templates_table";
import ProviderAliasesRow from "./provider_aliases_table";
import ProviderApiKeysRow from "./provider_api_keys_table";
import ProvidersRow from "./providers_table";
import ResourcesRow from "./resources_table";
import SettingsRow from "./settings_table";
import SystemEventsRow from "./system_events_table";
import ToolLogsRow from "./tool_logs_table";
import TriggersRow from "./triggers_table";
import WorkItemsRow from "./work_items_table";
import WorkPlansRow from "./work_plans_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent_channels: __table({
    name: 'agent_channels',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'agent_channels_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentChannelsRow),
  agent_prompt_fragments: __table({
    name: 'agent_prompt_fragments',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'agent_prompt_fragments_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentPromptFragmentsRow),
  agent_workspace_mounts: __table({
    name: 'agent_workspace_mounts',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'agent_workspace_mounts_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentWorkspaceMountsRow),
  agents: __table({
    name: 'agents',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'agents_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentsRow),
  alert_rules: __table({
    name: 'alert_rules',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'alert_rules_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AlertRulesRow),
  alerts: __table({
    name: 'alerts',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'alerts_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AlertsRow),
  approvals: __table({
    name: 'approvals',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'approvals_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApprovalsRow),
  component_resources: __table({
    name: 'component_resources',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'component_resources_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentResourcesRow),
  component_scripts: __table({
    name: 'component_scripts',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'component_scripts_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentScriptsRow),
  component_secrets: __table({
    name: 'component_secrets',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'component_secrets_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentSecretsRow),
  components: __table({
    name: 'components',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'components_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentsRow),
  conversationMessages: __table({
    name: 'conversation_messages',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'conversation_messages_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationMessagesRow),
  conversations: __table({
    name: 'conversations',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'conversations_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationsRow),
  environment_approvers: __table({
    name: 'environment_approvers',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'environment_approvers_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnvironmentApproversRow),
  environment_history: __table({
    name: 'environment_history',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'environment_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnvironmentHistoryRow),
  environments: __table({
    name: 'environments',
    indexes: [
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'environments_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, EnvironmentsRow),
  llm_models: __table({
    name: 'llm_models',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'llm_models_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LlmModelsRow),
  mcp_servers: __table({
    name: 'mcp_servers',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'mcp_servers_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, McpServersRow),
  messages: __table({
    name: 'messages',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'messages_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessagesRow),
  promotions: __table({
    name: 'promotions',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'promotions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PromotionsRow),
  prompt_fragment_versions: __table({
    name: 'prompt_fragment_versions',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prompt_fragment_versions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PromptFragmentVersionsRow),
  prompt_fragments: __table({
    name: 'prompt_fragments',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prompt_fragments_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PromptFragmentsRow),
  prompt_template_versions: __table({
    name: 'prompt_template_versions',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prompt_template_versions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PromptTemplateVersionsRow),
  prompt_templates: __table({
    name: 'prompt_templates',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prompt_templates_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PromptTemplatesRow),
  provider_aliases: __table({
    name: 'provider_aliases',
    indexes: [
      { name: 'alias', algorithm: 'btree', columns: [
        'alias',
      ] },
    ],
    constraints: [
      { name: 'provider_aliases_alias_key', constraint: 'unique', columns: ['alias'] },
    ],
  }, ProviderAliasesRow),
  provider_api_keys: __table({
    name: 'provider_api_keys',
    indexes: [
      { name: 'providerId', algorithm: 'btree', columns: [
        'providerId',
      ] },
    ],
    constraints: [
      { name: 'provider_api_keys_provider_id_key', constraint: 'unique', columns: ['providerId'] },
    ],
  }, ProviderApiKeysRow),
  providers: __table({
    name: 'providers',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'providers_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProvidersRow),
  resources: __table({
    name: 'resources',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'resources_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ResourcesRow),
  settings: __table({
    name: 'settings',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'settings_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SettingsRow),
  system_events: __table({
    name: 'system_events',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'system_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SystemEventsRow),
  tool_logs: __table({
    name: 'tool_logs',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tool_logs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ToolLogsRow),
  triggers: __table({
    name: 'triggers',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'triggers_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TriggersRow),
  workItems: __table({
    name: 'work_items',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'work_items_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorkItemsRow),
  workPlans: __table({
    name: 'work_plans',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'work_plans_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorkPlansRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_agent", AddAgentReducer),
  __reducerSchema("add_agent_channel", AddAgentChannelReducer),
  __reducerSchema("add_agent_mount", AddAgentMountReducer),
  __reducerSchema("add_agent_prompt_fragment", AddAgentPromptFragmentReducer),
  __reducerSchema("add_conversation_message", AddConversationMessageReducer),
  __reducerSchema("add_mcp_server", AddMcpServerReducer),
  __reducerSchema("add_model", AddModelReducer),
  __reducerSchema("add_prompt_fragment", AddPromptFragmentReducer),
  __reducerSchema("add_prompt_fragment_version", AddPromptFragmentVersionReducer),
  __reducerSchema("add_prompt_template", AddPromptTemplateReducer),
  __reducerSchema("add_prompt_template_version", AddPromptTemplateVersionReducer),
  __reducerSchema("add_provider", AddProviderReducer),
  __reducerSchema("add_work_item", AddWorkItemReducer),
  __reducerSchema("add_component_resource", AddComponentResourceReducer),
  __reducerSchema("add_component_script", AddComponentScriptReducer),
  __reducerSchema("add_component_secret", AddComponentSecretReducer),
  __reducerSchema("add_deployment_approver", AddDeploymentApproverReducer),
  __reducerSchema("consume_system_event", ConsumeSystemEventReducer),
  __reducerSchema("create_conversation", CreateConversationReducer),
  __reducerSchema("create_work_plan", CreateWorkPlanReducer),
  __reducerSchema("create_alert_rule", CreateAlertRuleReducer),
  __reducerSchema("create_component", CreateComponentReducer),
  __reducerSchema("create_deployment_environment", CreateDeploymentEnvironmentReducer),
  __reducerSchema("create_deployment_resource", CreateDeploymentResourceReducer),
  __reducerSchema("create_deployment_trigger", CreateDeploymentTriggerReducer),
  __reducerSchema("create_monitoring_alert", CreateMonitoringAlertReducer),
  __reducerSchema("deactivate_component", DeactivateComponentReducer),
  __reducerSchema("delete_agent", DeleteAgentReducer),
  __reducerSchema("delete_agent_channels_for_agent", DeleteAgentChannelsForAgentReducer),
  __reducerSchema("delete_agent_mounts_for_agent", DeleteAgentMountsForAgentReducer),
  __reducerSchema("delete_agent_prompt_fragment", DeleteAgentPromptFragmentReducer),
  __reducerSchema("delete_conversation", DeleteConversationReducer),
  __reducerSchema("delete_conversation_message", DeleteConversationMessageReducer),
  __reducerSchema("delete_mcp_server", DeleteMcpServerReducer),
  __reducerSchema("delete_prompt_fragment", DeletePromptFragmentReducer),
  __reducerSchema("delete_prompt_template", DeletePromptTemplateReducer),
  __reducerSchema("delete_provider", DeleteProviderReducer),
  __reducerSchema("delete_provider_alias", DeleteProviderAliasReducer),
  __reducerSchema("delete_provider_api_key", DeleteProviderApiKeyReducer),
  __reducerSchema("delete_setting", DeleteSettingReducer),
  __reducerSchema("delete_work_plan", DeleteWorkPlanReducer),
  __reducerSchema("delete_alert_rule", DeleteAlertRuleReducer),
  __reducerSchema("delete_deployment_resource", DeleteDeploymentResourceReducer),
  __reducerSchema("delete_deployment_trigger", DeleteDeploymentTriggerReducer),
  __reducerSchema("disable_alert_rule", DisableAlertRuleReducer),
  __reducerSchema("enable_alert_rule", EnableAlertRuleReducer),
  __reducerSchema("enqueue_system_event", EnqueueSystemEventReducer),
  __reducerSchema("import_conversation", ImportConversationReducer),
  __reducerSchema("import_conversation_message", ImportConversationMessageReducer),
  __reducerSchema("import_work_item", ImportWorkItemReducer),
  __reducerSchema("import_work_plan", ImportWorkPlanReducer),
  __reducerSchema("initiate_promotion", InitiatePromotionReducer),
  __reducerSchema("log_tool", LogToolReducer),
  __reducerSchema("record_approval", RecordApprovalReducer),
  __reducerSchema("remove_component_resource", RemoveComponentResourceReducer),
  __reducerSchema("remove_component_script", RemoveComponentScriptReducer),
  __reducerSchema("remove_component_secret", RemoveComponentSecretReducer),
  __reducerSchema("remove_deployment_approver", RemoveDeploymentApproverReducer),
  __reducerSchema("rename_work_item", RenameWorkItemReducer),
  __reducerSchema("resolve_monitoring_alert", ResolveMonitoringAlertReducer),
  __reducerSchema("save_message", SaveMessageReducer),
  __reducerSchema("set_default_agent", SetDefaultAgentReducer),
  __reducerSchema("set_provider_alias", SetProviderAliasReducer),
  __reducerSchema("set_provider_api_key", SetProviderApiKeyReducer),
  __reducerSchema("set_setting", SetSettingReducer),
  __reducerSchema("update_agent", UpdateAgentReducer),
  __reducerSchema("update_conversation", UpdateConversationReducer),
  __reducerSchema("update_mcp_server", UpdateMcpServerReducer),
  __reducerSchema("update_provider", UpdateProviderReducer),
  __reducerSchema("update_work_item", UpdateWorkItemReducer),
  __reducerSchema("update_work_plan_status", UpdateWorkPlanStatusReducer),
  __reducerSchema("update_alert_rule", UpdateAlertRuleReducer),
  __reducerSchema("update_component", UpdateComponentReducer),
  __reducerSchema("update_deployment_environment", UpdateDeploymentEnvironmentReducer),
  __reducerSchema("update_deployment_resource", UpdateDeploymentResourceReducer),
  __reducerSchema("update_deployment_trigger", UpdateDeploymentTriggerReducer),
  __reducerSchema("update_promotion_status", UpdatePromotionStatusReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

