// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  fragmentId: __t.string().name("fragment_id"),
  version: __t.u32(),
  content: __t.string(),
  changeReason: __t.string().name("change_reason"),
  changedBy: __t.string().name("changed_by"),
  createdAt: __t.u64().name("created_at"),
});
