// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  displayName: __t.string().name("display_name"),
  litellmPrefix: __t.string().name("litellm_prefix"),
  apiBaseUrl: __t.option(__t.string()).name("api_base_url"),
  modelsEndpoint: __t.option(__t.string()).name("models_endpoint"),
  modelsFetchMethod: __t.string().name("models_fetch_method"),
  authType: __t.string().name("auth_type"),
  isEnabled: __t.bool().name("is_enabled"),
  config: __t.string(),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
