// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  resourceType: __t.string().name("resource_type"),
  environment: __t.string(),
  connectionJson: __t.string().name("connection_json"),
  capabilitiesJson: __t.string().name("capabilities_json"),
  stateJson: __t.string().name("state_json"),
  tagsJson: __t.string().name("tags_json"),
  recommendationsJson: __t.string().name("recommendations_json"),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  lastProbedAt: __t.u64().name("last_probed_at"),
});
