// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  conversationId: __t.string().name("conversation_id"),
  agentId: __t.string().name("agent_id"),
  eventType: __t.string().name("event_type"),
  summary: __t.string(),
  metadata: __t.string(),
  consumed: __t.bool(),
  createdAt: __t.u64().name("created_at"),
});
