// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  componentType: __t.option(__t.string()),
  parentId: __t.option(__t.string()),
  runtime: __t.option(__t.string()),
  framework: __t.option(__t.string()),
  repositoryUrl: __t.option(__t.string()),
  icon: __t.option(__t.string()),
  description: __t.option(__t.string()),
  discoveredFrom: __t.option(__t.string()),
};
