// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAgentReducer from "../add_agent_reducer";
import AddConversationMessageReducer from "../add_conversation_message_reducer";
import CreateConversationReducer from "../create_conversation_reducer";
import DeleteConversationReducer from "../delete_conversation_reducer";
import DeleteConversationMessageReducer from "../delete_conversation_message_reducer";
import ImportConversationReducer from "../import_conversation_reducer";
import ImportConversationMessageReducer from "../import_conversation_message_reducer";
import LogToolReducer from "../log_tool_reducer";
import SaveMessageReducer from "../save_message_reducer";
import UpdateConversationReducer from "../update_conversation_reducer";

export type AddAgentParams = __Infer<typeof AddAgentReducer>;
export type AddConversationMessageParams = __Infer<typeof AddConversationMessageReducer>;
export type CreateConversationParams = __Infer<typeof CreateConversationReducer>;
export type DeleteConversationParams = __Infer<typeof DeleteConversationReducer>;
export type DeleteConversationMessageParams = __Infer<typeof DeleteConversationMessageReducer>;
export type ImportConversationParams = __Infer<typeof ImportConversationReducer>;
export type ImportConversationMessageParams = __Infer<typeof ImportConversationMessageReducer>;
export type LogToolParams = __Infer<typeof LogToolReducer>;
export type SaveMessageParams = __Infer<typeof SaveMessageReducer>;
export type UpdateConversationParams = __Infer<typeof UpdateConversationReducer>;

