// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAgentReducer from "../add_agent_reducer";
import AddAgentMountReducer from "../add_agent_mount_reducer";
import AddAgentPromptFragmentReducer from "../add_agent_prompt_fragment_reducer";
import AddConversationMessageReducer from "../add_conversation_message_reducer";
import AddMcpServerReducer from "../add_mcp_server_reducer";
import AddModelReducer from "../add_model_reducer";
import AddPromptFragmentReducer from "../add_prompt_fragment_reducer";
import AddPromptFragmentVersionReducer from "../add_prompt_fragment_version_reducer";
import AddPromptTemplateReducer from "../add_prompt_template_reducer";
import AddPromptTemplateVersionReducer from "../add_prompt_template_version_reducer";
import AddProviderReducer from "../add_provider_reducer";
import AddWorkItemReducer from "../add_work_item_reducer";
import ConsumeSystemEventReducer from "../consume_system_event_reducer";
import CreateConversationReducer from "../create_conversation_reducer";
import CreateWorkPlanReducer from "../create_work_plan_reducer";
import DeleteAgentPromptFragmentReducer from "../delete_agent_prompt_fragment_reducer";
import DeleteConversationReducer from "../delete_conversation_reducer";
import DeleteConversationMessageReducer from "../delete_conversation_message_reducer";
import DeleteMcpServerReducer from "../delete_mcp_server_reducer";
import DeletePromptFragmentReducer from "../delete_prompt_fragment_reducer";
import DeletePromptTemplateReducer from "../delete_prompt_template_reducer";
import DeleteProviderReducer from "../delete_provider_reducer";
import DeleteProviderAliasReducer from "../delete_provider_alias_reducer";
import DeleteProviderApiKeyReducer from "../delete_provider_api_key_reducer";
import DeleteSettingReducer from "../delete_setting_reducer";
import DeleteWorkPlanReducer from "../delete_work_plan_reducer";
import EnqueueSystemEventReducer from "../enqueue_system_event_reducer";
import ImportConversationReducer from "../import_conversation_reducer";
import ImportConversationMessageReducer from "../import_conversation_message_reducer";
import ImportWorkItemReducer from "../import_work_item_reducer";
import ImportWorkPlanReducer from "../import_work_plan_reducer";
import LogToolReducer from "../log_tool_reducer";
import RenameWorkItemReducer from "../rename_work_item_reducer";
import SaveMessageReducer from "../save_message_reducer";
import SetProviderAliasReducer from "../set_provider_alias_reducer";
import SetProviderApiKeyReducer from "../set_provider_api_key_reducer";
import SetSettingReducer from "../set_setting_reducer";
import UpdateConversationReducer from "../update_conversation_reducer";
import UpdateMcpServerReducer from "../update_mcp_server_reducer";
import UpdateProviderReducer from "../update_provider_reducer";
import UpdateWorkItemReducer from "../update_work_item_reducer";
import UpdateWorkPlanStatusReducer from "../update_work_plan_status_reducer";

export type AddAgentParams = __Infer<typeof AddAgentReducer>;
export type AddAgentMountParams = __Infer<typeof AddAgentMountReducer>;
export type AddAgentPromptFragmentParams = __Infer<typeof AddAgentPromptFragmentReducer>;
export type AddConversationMessageParams = __Infer<typeof AddConversationMessageReducer>;
export type AddMcpServerParams = __Infer<typeof AddMcpServerReducer>;
export type AddModelParams = __Infer<typeof AddModelReducer>;
export type AddPromptFragmentParams = __Infer<typeof AddPromptFragmentReducer>;
export type AddPromptFragmentVersionParams = __Infer<typeof AddPromptFragmentVersionReducer>;
export type AddPromptTemplateParams = __Infer<typeof AddPromptTemplateReducer>;
export type AddPromptTemplateVersionParams = __Infer<typeof AddPromptTemplateVersionReducer>;
export type AddProviderParams = __Infer<typeof AddProviderReducer>;
export type AddWorkItemParams = __Infer<typeof AddWorkItemReducer>;
export type ConsumeSystemEventParams = __Infer<typeof ConsumeSystemEventReducer>;
export type CreateConversationParams = __Infer<typeof CreateConversationReducer>;
export type CreateWorkPlanParams = __Infer<typeof CreateWorkPlanReducer>;
export type DeleteAgentPromptFragmentParams = __Infer<typeof DeleteAgentPromptFragmentReducer>;
export type DeleteConversationParams = __Infer<typeof DeleteConversationReducer>;
export type DeleteConversationMessageParams = __Infer<typeof DeleteConversationMessageReducer>;
export type DeleteMcpServerParams = __Infer<typeof DeleteMcpServerReducer>;
export type DeletePromptFragmentParams = __Infer<typeof DeletePromptFragmentReducer>;
export type DeletePromptTemplateParams = __Infer<typeof DeletePromptTemplateReducer>;
export type DeleteProviderParams = __Infer<typeof DeleteProviderReducer>;
export type DeleteProviderAliasParams = __Infer<typeof DeleteProviderAliasReducer>;
export type DeleteProviderApiKeyParams = __Infer<typeof DeleteProviderApiKeyReducer>;
export type DeleteSettingParams = __Infer<typeof DeleteSettingReducer>;
export type DeleteWorkPlanParams = __Infer<typeof DeleteWorkPlanReducer>;
export type EnqueueSystemEventParams = __Infer<typeof EnqueueSystemEventReducer>;
export type ImportConversationParams = __Infer<typeof ImportConversationReducer>;
export type ImportConversationMessageParams = __Infer<typeof ImportConversationMessageReducer>;
export type ImportWorkItemParams = __Infer<typeof ImportWorkItemReducer>;
export type ImportWorkPlanParams = __Infer<typeof ImportWorkPlanReducer>;
export type LogToolParams = __Infer<typeof LogToolReducer>;
export type RenameWorkItemParams = __Infer<typeof RenameWorkItemReducer>;
export type SaveMessageParams = __Infer<typeof SaveMessageReducer>;
export type SetProviderAliasParams = __Infer<typeof SetProviderAliasReducer>;
export type SetProviderApiKeyParams = __Infer<typeof SetProviderApiKeyReducer>;
export type SetSettingParams = __Infer<typeof SetSettingReducer>;
export type UpdateConversationParams = __Infer<typeof UpdateConversationReducer>;
export type UpdateMcpServerParams = __Infer<typeof UpdateMcpServerReducer>;
export type UpdateProviderParams = __Infer<typeof UpdateProviderReducer>;
export type UpdateWorkItemParams = __Infer<typeof UpdateWorkItemReducer>;
export type UpdateWorkPlanStatusParams = __Infer<typeof UpdateWorkPlanStatusReducer>;

