// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  workspaceId: __t.string(),
  edgeId: __t.string(),
  nodeId: __t.string(),
  provenanceType: __t.string(),
  sourcePath: __t.string(),
  sourceLineStart: __t.u32(),
  sourceLineEnd: __t.u32(),
  sourceRef: __t.string(),
  excerpt: __t.string(),
};
