// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  category: __t.string(),
  content: __t.string(),
  description: __t.string(),
  isActive: __t.bool().name("is_active"),
  isSystem: __t.bool().name("is_system"),
  summary: __t.string(),
  tier: __t.string(),
  taskTriggers: __t.string().name("task_triggers"),
  tokenEstimate: __t.u32().name("token_estimate"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
