// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.option(__t.string()),
  metric: __t.option(__t.string()),
  operator: __t.option(__t.string()),
  threshold: __t.option(__t.f64()),
  durationMinutes: __t.option(__t.u32()),
  severity: __t.option(__t.string()),
  autoFileIssue: __t.option(__t.bool()),
  customScriptId: __t.option(__t.string()),
  appliesToResources: __t.option(__t.string()),
  componentId: __t.option(__t.string()),
};
