// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  scriptId: __t.option(__t.string()),
  repoUrl: __t.option(__t.string()),
  branch: __t.option(__t.string()),
  tagPattern: __t.option(__t.string()),
  environment: __t.option(__t.string()),
  cronSchedule: __t.option(__t.string()),
  enabled: __t.option(__t.bool()),
};
