// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  repoId: __t.string().name("repo_id"),
  path: __t.string(),
  contentHash: __t.string().name("content_hash"),
  language: __t.string(),
  mtimeNs: __t.u64().name("mtime_ns"),
  sizeBytes: __t.u64().name("size_bytes"),
  lastIndexedAt: __t.u64().name("last_indexed_at"),
  lastRunId: __t.string().name("last_run_id"),
  status: __t.string(),
  lastError: __t.string().name("last_error"),
  metadata: __t.string(),
});
