// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  category: __t.string(),
  content: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
  isSystem: __t.bool(),
  summary: __t.string(),
  tier: __t.string(),
  taskTriggers: __t.string(),
  tokenEstimate: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
};
