// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentChannels = __t.object("AgentChannels", {
  id: __t.string(),
  agentId: __t.string(),
  channel: __t.string(),
  sandboxOverride: __t.string(),
  enabled: __t.bool(),
  createdAt: __t.u64(),
});
export type AgentChannels = __Infer<typeof AgentChannels>;

export const AgentDatabaseAccess = __t.object("AgentDatabaseAccess", {
  id: __t.string(),
  agentId: __t.string(),
  databaseId: __t.string(),
  accessTier: __t.string(),
  faucetApiKeyVaultRef: __t.string(),
  faucetRoleName: __t.string(),
  status: __t.string(),
  assignedAt: __t.u64(),
});
export type AgentDatabaseAccess = __Infer<typeof AgentDatabaseAccess>;

export const AgentPromptFragments = __t.object("AgentPromptFragments", {
  id: __t.string(),
  agentId: __t.string(),
  fragmentId: __t.string(),
  rank: __t.u32(),
  enabled: __t.bool(),
  createdAt: __t.u64(),
});
export type AgentPromptFragments = __Infer<typeof AgentPromptFragments>;

export const AgentWorkspaceMounts = __t.object("AgentWorkspaceMounts", {
  id: __t.string(),
  agentId: __t.string(),
  hostPath: __t.string(),
  mountName: __t.string(),
  containerPath: __t.string(),
  readonly: __t.bool(),
});
export type AgentWorkspaceMounts = __Infer<typeof AgentWorkspaceMounts>;

export const Agents = __t.object("Agents", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  systemPrompt: __t.string(),
  model: __t.string(),
  utilityModel: __t.string(),
  tools: __t.string(),
  sandboxImage: __t.string(),
  maxIterations: __t.u32(),
  isActive: __t.bool(),
  isDefault: __t.bool(),
  createdAt: __t.u64(),
});
export type Agents = __Infer<typeof Agents>;

export const AlertRules = __t.object("AlertRules", {
  id: __t.string(),
  environment: __t.string(),
  name: __t.string(),
  metric: __t.string(),
  operator: __t.string(),
  threshold: __t.f64(),
  durationMinutes: __t.u32(),
  severity: __t.string(),
  enabled: __t.bool(),
  autoFileIssue: __t.bool(),
  customScriptId: __t.string(),
  appliesToResources: __t.string(),
  componentId: __t.string(),
  triggeredCount: __t.u32(),
  lastTriggeredAt: __t.u64(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type AlertRules = __Infer<typeof AlertRules>;

export const Alerts = __t.object("Alerts", {
  id: __t.string(),
  environment: __t.string(),
  category: __t.string(),
  component: __t.string(),
  componentId: __t.string(),
  fingerprintHash: __t.string(),
  severity: __t.string(),
  message: __t.string(),
  detectedAt: __t.u64(),
  issueNumber: __t.u32(),
  issueAction: __t.string(),
  resolvedAt: __t.u64(),
});
export type Alerts = __Infer<typeof Alerts>;

export const Approvals = __t.object("Approvals", {
  id: __t.string(),
  promotionId: __t.string(),
  scriptId: __t.string(),
  scriptVersion: __t.string(),
  environmentName: __t.string(),
  userId: __t.string(),
  approvedAt: __t.u64(),
});
export type Approvals = __Infer<typeof Approvals>;

export const ComponentResources = __t.object("ComponentResources", {
  id: __t.string(),
  componentId: __t.string(),
  resourceId: __t.string(),
  environment: __t.string(),
  port: __t.u32(),
  processName: __t.string(),
  healthCheck: __t.string(),
  createdAt: __t.u64(),
});
export type ComponentResources = __Infer<typeof ComponentResources>;

export const ComponentScripts = __t.object("ComponentScripts", {
  id: __t.string(),
  componentId: __t.string(),
  scriptId: __t.string(),
  role: __t.string(),
  createdAt: __t.u64(),
});
export type ComponentScripts = __Infer<typeof ComponentScripts>;

export const ComponentSecrets = __t.object("ComponentSecrets", {
  id: __t.string(),
  componentId: __t.string(),
  secretKey: __t.string(),
  environment: __t.string(),
  isSensitive: __t.bool(),
  createdAt: __t.u64(),
});
export type ComponentSecrets = __Infer<typeof ComponentSecrets>;

export const Components = __t.object("Components", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  componentType: __t.string(),
  parentId: __t.string(),
  runtime: __t.string(),
  framework: __t.string(),
  repositoryUrl: __t.string(),
  icon: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  discoveredFrom: __t.string(),
  sourcePath: __t.string(),
});
export type Components = __Infer<typeof Components>;

export const ConversationMessages = __t.object("ConversationMessages", {
  id: __t.string(),
  conversationId: __t.string(),
  role: __t.string(),
  content: __t.string(),
  toolCalls: __t.string(),
  toolCallId: __t.string(),
  tokenCount: __t.u32(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type ConversationMessages = __Infer<typeof ConversationMessages>;

export const Conversations = __t.object("Conversations", {
  id: __t.string(),
  agentId: __t.string(),
  channel: __t.string(),
  title: __t.string(),
  isActive: __t.bool(),
  messageCount: __t.u32(),
  rollingSummary: __t.string(),
  summaryCoversto: __t.u32(),
  recentToolsUsed: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Conversations = __Infer<typeof Conversations>;

export const DatabaseConnections = __t.object("DatabaseConnections", {
  id: __t.string(),
  name: __t.string(),
  driver: __t.string(),
  description: __t.string(),
  status: __t.string(),
  dsnVaultRef: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DatabaseConnections = __Infer<typeof DatabaseConnections>;

export const EmbeddingModels = __t.object("EmbeddingModels", {
  modelName: __t.string(),
  family: __t.string(),
  provider: __t.string(),
  maxDimension: __t.u32(),
  supportedDimensions: __t.string(),
  supportsLocal: __t.bool(),
  supportsApi: __t.bool(),
  isDefault: __t.bool(),
  createdAt: __t.u64(),
});
export type EmbeddingModels = __Infer<typeof EmbeddingModels>;

export const EnvironmentApprovers = __t.object("EnvironmentApprovers", {
  id: __t.string(),
  environmentName: __t.string(),
  userId: __t.string(),
  addedAt: __t.u64(),
  addedBy: __t.string(),
});
export type EnvironmentApprovers = __Infer<typeof EnvironmentApprovers>;

export const EnvironmentHistory = __t.object("EnvironmentHistory", {
  id: __t.string(),
  environmentName: __t.string(),
  action: __t.string(),
  changedBy: __t.string(),
  changedAt: __t.u64(),
  beforeState: __t.string(),
  afterState: __t.string(),
});
export type EnvironmentHistory = __Infer<typeof EnvironmentHistory>;

export const Environments = __t.object("Environments", {
  name: __t.string(),
  displayName: __t.string(),
  order: __t.u32(),
  isActive: __t.bool(),
  maxScriptTimeout: __t.u32(),
  healthCheckInterval: __t.u32(),
  windowDays: __t.string(),
  windowStart: __t.string(),
  windowEnd: __t.string(),
  windowTimezone: __t.string(),
  requiredApprovals: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Environments = __Infer<typeof Environments>;

export const LlmModels = __t.object("LlmModels", {
  id: __t.string(),
  provider: __t.string(),
  modelId: __t.string(),
  displayName: __t.string(),
  contextWindow: __t.u32(),
  isEnabled: __t.bool(),
});
export type LlmModels = __Infer<typeof LlmModels>;

export const McpServers = __t.object("McpServers", {
  id: __t.string(),
  name: __t.string(),
  command: __t.string(),
  args: __t.string(),
  env: __t.string(),
  enabled: __t.bool(),
  agentId: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type McpServers = __Infer<typeof McpServers>;

export const Messages = __t.object("Messages", {
  id: __t.string(),
  agentId: __t.string(),
  sessionId: __t.string(),
  role: __t.string(),
  content: __t.string(),
  metadata: __t.string(),
  createdAt: __t.u64(),
});
export type Messages = __Infer<typeof Messages>;

export const Promotions = __t.object("Promotions", {
  id: __t.string(),
  scriptId: __t.string(),
  scriptVersion: __t.string(),
  scriptSha256: __t.string(),
  environmentName: __t.string(),
  status: __t.string(),
  initiatedBy: __t.string(),
  initiatedAt: __t.u64(),
  promotedAt: __t.u64(),
  deployedAt: __t.u64(),
  receiptId: __t.string(),
});
export type Promotions = __Infer<typeof Promotions>;

export const PromptFragmentVersions = __t.object("PromptFragmentVersions", {
  id: __t.string(),
  fragmentId: __t.string(),
  version: __t.u32(),
  content: __t.string(),
  changeReason: __t.string(),
  changedBy: __t.string(),
  createdAt: __t.u64(),
});
export type PromptFragmentVersions = __Infer<typeof PromptFragmentVersions>;

export const PromptFragments = __t.object("PromptFragments", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  category: __t.string(),
  content: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
  isSystem: __t.bool(),
  summary: __t.string(),
  tier: __t.string(),
  taskTriggers: __t.string(),
  tokenEstimate: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type PromptFragments = __Infer<typeof PromptFragments>;

export const PromptTemplateVersions = __t.object("PromptTemplateVersions", {
  id: __t.string(),
  templateId: __t.string(),
  version: __t.u32(),
  content: __t.string(),
  changeReason: __t.string(),
  changedBy: __t.string(),
  createdAt: __t.u64(),
});
export type PromptTemplateVersions = __Infer<typeof PromptTemplateVersions>;

export const PromptTemplates = __t.object("PromptTemplates", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  category: __t.string(),
  content: __t.string(),
  variables: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type PromptTemplates = __Infer<typeof PromptTemplates>;

export const ProviderAliases = __t.object("ProviderAliases", {
  alias: __t.string(),
  providerId: __t.string(),
});
export type ProviderAliases = __Infer<typeof ProviderAliases>;

export const ProviderApiKeys = __t.object("ProviderApiKeys", {
  providerId: __t.string(),
  encryptedValue: __t.string(),
  keyType: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ProviderApiKeys = __Infer<typeof ProviderApiKeys>;

export const Providers = __t.object("Providers", {
  id: __t.string(),
  displayName: __t.string(),
  litellmPrefix: __t.string(),
  apiBaseUrl: __t.option(__t.string()),
  modelsEndpoint: __t.option(__t.string()),
  modelsFetchMethod: __t.string(),
  authType: __t.string(),
  isEnabled: __t.bool(),
  config: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Providers = __Infer<typeof Providers>;

export const ResourceEnvironments = __t.object("ResourceEnvironments", {
  id: __t.string(),
  resourceId: __t.string(),
  environmentName: __t.string(),
  createdAt: __t.u64(),
});
export type ResourceEnvironments = __Infer<typeof ResourceEnvironments>;

export const Resources = __t.object("Resources", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  resourceType: __t.string(),
  environment: __t.string(),
  connectionJson: __t.string(),
  capabilitiesJson: __t.string(),
  stateJson: __t.string(),
  tagsJson: __t.string(),
  recommendationsJson: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  lastProbedAt: __t.u64(),
});
export type Resources = __Infer<typeof Resources>;

export const Settings = __t.object("Settings", {
  key: __t.string(),
  value: __t.string(),
  keyType: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Settings = __Infer<typeof Settings>;

export const SystemEvents = __t.object("SystemEvents", {
  id: __t.string(),
  conversationId: __t.string(),
  agentId: __t.string(),
  eventType: __t.string(),
  summary: __t.string(),
  metadata: __t.string(),
  consumed: __t.bool(),
  createdAt: __t.u64(),
});
export type SystemEvents = __Infer<typeof SystemEvents>;

export const ToolLogs = __t.object("ToolLogs", {
  id: __t.string(),
  agentId: __t.string(),
  sessionId: __t.string(),
  toolName: __t.string(),
  input: __t.string(),
  output: __t.string(),
  duration: __t.u32(),
  createdAt: __t.u64(),
});
export type ToolLogs = __Infer<typeof ToolLogs>;

export const Triggers = __t.object("Triggers", {
  id: __t.string(),
  scriptId: __t.string(),
  repoUrl: __t.string(),
  branch: __t.string(),
  tagPattern: __t.string(),
  environment: __t.string(),
  cronSchedule: __t.string(),
  enabled: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Triggers = __Infer<typeof Triggers>;

export const WorkItems = __t.object("WorkItems", {
  id: __t.string(),
  planId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  ordinal: __t.u32(),
  contextSnapshot: __t.string(),
  notes: __t.string(),
  filesChanged: __t.string(),
  startedAt: __t.option(__t.u64()),
  completedAt: __t.option(__t.u64()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  description: __t.string(),
});
export type WorkItems = __Infer<typeof WorkItems>;

export const WorkPlans = __t.object("WorkPlans", {
  id: __t.string(),
  agentId: __t.string(),
  conversationId: __t.string(),
  parentPlanId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  completedAt: __t.option(__t.u64()),
});
export type WorkPlans = __Infer<typeof WorkPlans>;

