// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  repoId: __t.string().name("repo_id"),
  nodeType: __t.string().name("node_type"),
  stableKey: __t.string().name("stable_key"),
  displayName: __t.string().name("display_name"),
  path: __t.string(),
  language: __t.string(),
  signature: __t.string(),
  contentHash: __t.string().name("content_hash"),
  isDeleted: __t.bool().name("is_deleted"),
  metadata: __t.string(),
  embeddingModel: __t.string().name("embedding_model"),
  processedAt: __t.u64().name("processed_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
