// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  edgeId: __t.string().name("edge_id"),
  nodeId: __t.string().name("node_id"),
  provenanceType: __t.string().name("provenance_type"),
  sourcePath: __t.string().name("source_path"),
  sourceLineStart: __t.u32().name("source_line_start"),
  sourceLineEnd: __t.u32().name("source_line_end"),
  sourceRef: __t.string().name("source_ref"),
  excerpt: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
