// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAgentReducer from "../add_agent_reducer";
import LogToolReducer from "../log_tool_reducer";
import SaveMessageReducer from "../save_message_reducer";

export type AddAgentParams = __Infer<typeof AddAgentReducer>;
export type LogToolParams = __Infer<typeof LogToolReducer>;
export type SaveMessageParams = __Infer<typeof SaveMessageReducer>;

