// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  environment: __t.string(),
  category: __t.string(),
  component: __t.string(),
  componentId: __t.string().name("component_id"),
  fingerprintHash: __t.string().name("fingerprint_hash"),
  severity: __t.string(),
  message: __t.string(),
  detectedAt: __t.u64().name("detected_at"),
  issueNumber: __t.u32().name("issue_number"),
  issueAction: __t.string().name("issue_action"),
  resolvedAt: __t.u64().name("resolved_at"),
});
