// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  promotionId: __t.string().name("promotion_id"),
  scriptId: __t.string().name("script_id"),
  scriptVersion: __t.string().name("script_version"),
  environmentName: __t.string().name("environment_name"),
  userId: __t.string().name("user_id"),
  approvedAt: __t.u64().name("approved_at"),
});
