// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  componentId: __t.string().name("component_id"),
  resourceId: __t.string().name("resource_id"),
  environment: __t.string(),
  port: __t.u32(),
  processName: __t.string().name("process_name"),
  healthCheck: __t.string().name("health_check"),
  createdAt: __t.u64().name("created_at"),
});
