// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  componentType: __t.string().name("component_type"),
  parentId: __t.string().name("parent_id"),
  runtime: __t.string(),
  framework: __t.string(),
  repositoryUrl: __t.string().name("repository_url"),
  icon: __t.string(),
  description: __t.string(),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  discoveredFrom: __t.string().name("discovered_from"),
  sourcePath: __t.string().name("source_path"),
});
