// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  name: __t.string(),
  displayName: __t.string(),
  order: __t.u32(),
  maxScriptTimeout: __t.u32(),
  healthCheckInterval: __t.u32(),
  windowDays: __t.string(),
  windowStart: __t.string(),
  windowEnd: __t.string(),
  windowTimezone: __t.string(),
  requiredApprovals: __t.u32(),
  historyId: __t.string(),
  changedBy: __t.string(),
};
