// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  environment: __t.string(),
  name: __t.string(),
  metric: __t.string(),
  operator: __t.string(),
  threshold: __t.f64(),
  durationMinutes: __t.u32(),
  severity: __t.string(),
  enabled: __t.bool(),
  autoFileIssue: __t.bool(),
  customScriptId: __t.string(),
  appliesToResources: __t.string(),
  componentId: __t.string(),
};
