// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  scriptId: __t.string().name("script_id"),
  scriptVersion: __t.string().name("script_version"),
  scriptSha256: __t.string().name("script_sha_256"),
  environmentName: __t.string().name("environment_name"),
  status: __t.string(),
  initiatedBy: __t.string().name("initiated_by"),
  initiatedAt: __t.u64().name("initiated_at"),
  promotedAt: __t.u64().name("promoted_at"),
  deployedAt: __t.u64().name("deployed_at"),
  receiptId: __t.string().name("receipt_id"),
});
