// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  scriptId: __t.string().name("script_id"),
  repoUrl: __t.string().name("repo_url"),
  branch: __t.string(),
  tagPattern: __t.string().name("tag_pattern"),
  environment: __t.string(),
  cronSchedule: __t.string().name("cron_schedule"),
  enabled: __t.bool(),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
