// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  displayName: __t.option(__t.string()),
  resourceType: __t.option(__t.string()),
  environment: __t.option(__t.string()),
  connectionJson: __t.option(__t.string()),
  capabilitiesJson: __t.option(__t.string()),
  stateJson: __t.option(__t.string()),
  tagsJson: __t.option(__t.string()),
  recommendationsJson: __t.option(__t.string()),
  isActive: __t.option(__t.bool()),
  updatedAt: __t.u64(),
  lastProbedAt: __t.option(__t.u64()),
};
