// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  workspaceId: __t.string(),
  repoId: __t.string(),
  nodeType: __t.string(),
  stableKey: __t.string(),
  displayName: __t.string(),
  path: __t.string(),
  language: __t.string(),
  signature: __t.string(),
  contentHash: __t.string(),
  metadata: __t.string(),
  embeddingModel: __t.string(),
};
