// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  workspaceId: __t.string(),
  repoId: __t.string(),
  sourceNodeId: __t.string(),
  targetNodeId: __t.string(),
  edgeType: __t.string(),
  mode: __t.string(),
  confidence: __t.f64(),
  sourceKind: __t.string(),
  runId: __t.string(),
  metadata: __t.string(),
};
