// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  repoId: __t.string().name("repo_id"),
  runType: __t.string().name("run_type"),
  status: __t.string(),
  trigger: __t.string(),
  filesScanned: __t.u32().name("files_scanned"),
  nodesWritten: __t.u32().name("nodes_written"),
  edgesWritten: __t.u32().name("edges_written"),
  startedAt: __t.u64().name("started_at"),
  completedAt: __t.u64().name("completed_at"),
  error: __t.string(),
});
