import React from "react";

export const s: Record<string, React.CSSProperties> = {
  container: { display: "flex", flexDirection: "column", height: "100vh", maxWidth: "1200px", margin: "0 auto", width: "100%", overflow: "hidden", boxSizing: "border-box" as const },
  header: { display: "flex", alignItems: "center", gap: "16px", padding: "16px 24px", borderBottomWidth: "1px", borderBottomStyle: "solid", borderBottomColor: "#1e1e2e", flexShrink: 0 },
  backLink: { color: "#6c8aff", textDecoration: "none", fontSize: "0.9rem" },
  title: { fontSize: "1.5rem", fontWeight: 700, margin: 0 },
  tabBarWrapper: { position: "relative" as const, borderBottomWidth: "1px", borderBottomStyle: "solid" as const, borderBottomColor: "#1e1e2e", flexShrink: 0 },
  tabBar: { display: "flex", padding: "0 24px", overflowX: "auto" as const, scrollbarWidth: "none" as const, msOverflowStyle: "none" as const, WebkitOverflowScrolling: "touch" as const, flexWrap: "nowrap" as const },
  tabBarFade: { position: "absolute" as const, top: 0, right: 0, bottom: 0, width: "40px", background: "linear-gradient(to right, transparent, #0a0a12)", pointerEvents: "none" as const },
  tab: {
    background: "none", borderWidth: 0, borderStyle: "none", borderColor: "transparent", borderBottomWidth: "2px", borderBottomStyle: "solid" as const, borderBottomColor: "transparent",
    color: "#8888a0", padding: "12px 20px", fontSize: "0.9rem", fontWeight: 500,
    cursor: "pointer", transition: "color 0.2s, border-color 0.2s", whiteSpace: "nowrap" as const, flexShrink: 0,
  },
  tabActive: { color: "#6c8aff", borderBottomColor: "#6c8aff" },
  content: { flex: 1, overflowY: "auto" as const, padding: "24px", display: "flex", flexDirection: "column", gap: "24px", minHeight: 0, WebkitOverflowScrolling: "touch" as any, boxSizing: "border-box" as const },
  section: { backgroundColor: "#12121a", borderRadius: "12px", padding: "24px", borderWidth: "1px", borderStyle: "solid", borderColor: "#1e1e2e", overflow: "visible" as const, flexShrink: 0 },
  sectionTitle: { fontSize: "1.1rem", fontWeight: 600, color: "#6c8aff", margin: "0 0 20px 0" },
  field: { marginBottom: "16px" },
  label: { display: "block", fontSize: "0.85rem", color: "#8888a0", marginBottom: "6px", fontWeight: 500 },
  select: { width: "100%", backgroundColor: "#1e1e2e", borderWidth: "1px", borderStyle: "solid", borderColor: "#2a2a3e", borderRadius: "8px", padding: "10px 12px", color: "#e0e0e8", fontSize: "0.95rem", outline: "none" },
  input: { flex: 1, backgroundColor: "#1e1e2e", borderWidth: "1px", borderStyle: "solid", borderColor: "#2a2a3e", borderRadius: "8px", padding: "10px 12px", color: "#e0e0e8", fontSize: "0.95rem", outline: "none" },
  modelDetails: { display: "flex", gap: "16px", flexWrap: "wrap" as const, fontSize: "0.8rem", color: "#8888a0", marginBottom: "16px", padding: "8px 12px", backgroundColor: "#1e1e2e", borderRadius: "8px" },
  radioGroup: { display: "flex", gap: "20px" },
  radioLabel: { display: "flex", alignItems: "center", gap: "6px", color: "#e0e0e8", fontSize: "0.95rem", cursor: "pointer" },
  radio: { accentColor: "#6c8aff" },
  button: { backgroundColor: "#6c8aff", color: "#fff", borderWidth: 0, borderStyle: "none", borderColor: "transparent", borderRadius: "8px", padding: "10px 20px", fontSize: "0.9rem", fontWeight: 600, cursor: "pointer" },
  keyRow: { display: "flex", gap: "8px" },
  deleteBtn: { backgroundColor: "#3a1a1e", color: "#ff6c8a", borderWidth: "1px", borderStyle: "solid", borderColor: "#5a2a2e", borderRadius: "8px", padding: "10px 16px", cursor: "pointer", fontWeight: 500, fontSize: "0.9rem", whiteSpace: "nowrap" },
  masked: { color: "#6c8aff", fontSize: "0.8rem", marginLeft: "8px" },
  warning: { backgroundColor: "#2a2a1a", borderWidth: "1px", borderStyle: "solid", borderColor: "#aa8800", borderRadius: "8px", padding: "12px 16px", color: "#ffcc44", fontSize: "0.85rem", marginBottom: "16px" },
  helpText: { color: "#5a5a6e", fontSize: "0.8rem", margin: "0 0 8px 0", lineHeight: "1.4" },
  msg: { marginTop: "12px", fontSize: "0.85rem" },
  readOnly: { color: "#8888a0", fontSize: "0.95rem", padding: "10px 12px", backgroundColor: "#1e1e2e", borderRadius: "8px" },
};
