// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  agentId: __t.string().name("agent_id"),
  databaseId: __t.string().name("database_id"),
  accessTier: __t.string().name("access_tier"),
  faucetApiKeyVaultRef: __t.string().name("faucet_api_key_vault_ref"),
  faucetRoleName: __t.string().name("faucet_role_name"),
  status: __t.string(),
  assignedAt: __t.u64().name("assigned_at"),
});
