// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string().name("display_name"),
  systemPrompt: __t.string().name("system_prompt"),
  model: __t.string(),
  utilityModel: __t.string().name("utility_model"),
  tools: __t.string(),
  isActive: __t.bool().name("is_active"),
  isDefault: __t.bool().name("is_default"),
  createdAt: __t.u64().name("created_at"),
});
