// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  environment: __t.string(),
  name: __t.string(),
  metric: __t.string(),
  operator: __t.string(),
  threshold: __t.f64(),
  durationMinutes: __t.u32().name("duration_minutes"),
  severity: __t.string(),
  enabled: __t.bool(),
  autoFileIssue: __t.bool().name("auto_file_issue"),
  customScriptId: __t.string().name("custom_script_id"),
  appliesToResources: __t.string().name("applies_to_resources"),
  componentId: __t.string().name("component_id"),
  triggeredCount: __t.u32().name("triggered_count"),
  lastTriggeredAt: __t.u64().name("last_triggered_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
