// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  conversationId: __t.string().name("conversation_id"),
  role: __t.string(),
  content: __t.string(),
  toolCalls: __t.string().name("tool_calls"),
  toolCallId: __t.string().name("tool_call_id"),
  tokenCount: __t.u32().name("token_count"),
  status: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
