// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  environment: __t.string(),
  category: __t.string(),
  component: __t.string(),
  componentId: __t.string(),
  fingerprintHash: __t.string(),
  severity: __t.string(),
  message: __t.string(),
  detectedAt: __t.u64(),
  issueNumber: __t.u32(),
  issueAction: __t.string(),
};
