// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  modelName: __t.string().primaryKey().name("model_name"),
  family: __t.string(),
  provider: __t.string(),
  maxDimension: __t.u32().name("max_dimension"),
  supportedDimensions: __t.string().name("supported_dimensions"),
  supportsLocal: __t.bool().name("supports_local"),
  supportsApi: __t.bool().name("supports_api"),
  isDefault: __t.bool().name("is_default"),
  createdAt: __t.u64().name("created_at"),
});
