// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  name: __t.string().primaryKey(),
  displayName: __t.string().name("display_name"),
  order: __t.u32(),
  isActive: __t.bool().name("is_active"),
  maxScriptTimeout: __t.u32().name("max_script_timeout"),
  healthCheckInterval: __t.u32().name("health_check_interval"),
  windowDays: __t.string().name("window_days"),
  windowStart: __t.string().name("window_start"),
  windowEnd: __t.string().name("window_end"),
  windowTimezone: __t.string().name("window_timezone"),
  requiredApprovals: __t.u32().name("required_approvals"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
