// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  agentId: __t.string().name("agent_id"),
  sessionId: __t.string().name("session_id"),
  toolName: __t.string().name("tool_name"),
  input: __t.string(),
  output: __t.string(),
  duration: __t.u32(),
  createdAt: __t.u64().name("created_at"),
});
