// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agents = __t.object("Agents", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.string(),
  systemPrompt: __t.string(),
  model: __t.string(),
  utilityModel: __t.string(),
  tools: __t.string(),
  isActive: __t.bool(),
  isDefault: __t.bool(),
  createdAt: __t.u64(),
});
export type Agents = __Infer<typeof Agents>;

export const LlmModels = __t.object("LlmModels", {
  id: __t.string(),
  provider: __t.string(),
  modelId: __t.string(),
  displayName: __t.string(),
  contextWindow: __t.u32(),
  isEnabled: __t.bool(),
});
export type LlmModels = __Infer<typeof LlmModels>;

export const Messages = __t.object("Messages", {
  id: __t.string(),
  agentId: __t.string(),
  sessionId: __t.string(),
  role: __t.string(),
  content: __t.string(),
  metadata: __t.string(),
  createdAt: __t.u64(),
});
export type Messages = __Infer<typeof Messages>;

export const ToolLogs = __t.object("ToolLogs", {
  id: __t.string(),
  agentId: __t.string(),
  sessionId: __t.string(),
  toolName: __t.string(),
  input: __t.string(),
  output: __t.string(),
  duration: __t.u32(),
  createdAt: __t.u64(),
});
export type ToolLogs = __Infer<typeof ToolLogs>;

