// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  displayName: __t.option(__t.string()),
  litellmPrefix: __t.option(__t.string()),
  apiBaseUrl: __t.option(__t.string()),
  modelsEndpoint: __t.option(__t.string()),
  modelsFetchMethod: __t.option(__t.string()),
  authType: __t.option(__t.string()),
  isEnabled: __t.option(__t.bool()),
  config: __t.option(__t.string()),
  updatedAt: __t.u64(),
};
