// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  planId: __t.string().name("plan_id"),
  title: __t.string(),
  status: __t.string(),
  ordinal: __t.u32(),
  contextSnapshot: __t.string().name("context_snapshot"),
  notes: __t.string(),
  filesChanged: __t.string().name("files_changed"),
  startedAt: __t.option(__t.u64()).name("started_at"),
  completedAt: __t.option(__t.u64()).name("completed_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  description: __t.string(),
});
