/**
 * SpacetimeDB client for the Bond frontend.
 *
 * Provides a singleton connection and React-friendly subscription hooks.
 * The frontend subscribes directly to SpacetimeDB tables — when a reducer
 * inserts/updates/deletes a row, the subscription pushes the change
 * to the browser instantly.
 */

import { DbConnection } from "./spacetimedb/index";

// Types inferred from generated bindings
export interface Conversation {
  id: string;
  agentId: string;
  channel: string;
  title: string;
  isActive: boolean;
  messageCount: number;
  rollingSummary: string;
  summaryCoversto: number;
  recentToolsUsed: string;
  createdAt: bigint;
  updatedAt: bigint;
}

export interface ConversationMessage {
  id: string;
  conversationId: string;
  role: string;
  content: string;
  toolCalls: string;
  toolCallId: string;
  tokenCount: number;
  status: string;
  createdAt: bigint;
}

export interface WorkPlan {
  id: string;
  agentId: string;
  conversationId: string;
  title: string;
  status: string;
  createdAt: bigint;
  updatedAt: bigint;
}

export interface WorkItem {
  id: string;
  planId: string;
  title: string;
  status: string;
  ordinal: number;
  notes: string;
  filesChanged: string;
  createdAt: bigint;
  updatedAt: bigint;
}

// ── Singleton connection ──

let db: DbConnection | null = null;
let connectionPromise: Promise<DbConnection> | null = null;

type Listener = () => void;
const listeners: Set<Listener> = new Set();

export function onDataChange(fn: Listener): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function notifyListeners() {
  listeners.forEach((fn) => fn());
}

export function getConnection(): DbConnection | null {
  return db;
}

export async function connectToSpacetimeDB(
  uri = "ws://localhost:18787",
  moduleName = "bond-core-v2"
): Promise<DbConnection> {
  if (db) return db;
  if (connectionPromise) return connectionPromise;

  connectionPromise = new Promise<DbConnection>(async (resolve, reject) => {
    try {
      // Fetch CLI token from same-origin proxy endpoint
      let token: string | null = null;
      try {
        const res = await fetch("/api/stdb-ws-token", { method: "POST" });
        if (res.ok) {
          const data = await res.json();
          token = data.token || null;
        }
      } catch { }

      let builder = DbConnection.builder()
        .withUri(uri)
        .withDatabaseName(moduleName);

      if (token) {
        builder = builder.withToken(token);
      }

      const conn = builder
        .onConnect((ctx, identity, _authToken) => {
          console.log("[spacetimedb] Connected, identity:", identity.toHexString());
          db = conn;

          ctx.subscriptionBuilder()
            .onApplied(() => {
              const count = [...ctx.db.conversations.iter()].length;
              console.log(`[spacetimedb] Subscribed — \${count} conversations`);
              notifyListeners();
              resolve(conn);
            })
            .onError((errCtx) => {
              console.error("[spacetimedb] Subscription error:", errCtx?.event);
            })
            .subscribe([
              "SELECT * FROM conversations",
              "SELECT * FROM conversation_messages",
              "SELECT * FROM work_plans",
              "SELECT * FROM work_items",
              "SELECT * FROM agents",
              "SELECT * FROM agent_channels",
              "SELECT * FROM agent_workspace_mounts",
              "SELECT * FROM llm_models",
              "SELECT * FROM providers",
              "SELECT * FROM provider_aliases"
            ]);
        })
        .onConnectError((ctx, err) => {
          console.error("[spacetimedb] Connection failed:", err);
          connectionPromise = null;
          reject(err);
        })
        .build();

      // Table change listeners
      conn.db.conversations.onInsert(() => notifyListeners());
      conn.db.conversations.onUpdate(() => notifyListeners());
      conn.db.conversations.onDelete(() => notifyListeners());

      conn.db.conversationMessages.onInsert(() => notifyListeners());
      conn.db.conversationMessages.onDelete(() => notifyListeners());

      // Use camelCase property names generated by SpacetimeDB CLI (workPlans, workItems)
      if (conn.db.workPlans) {
        conn.db.workPlans.onInsert(() => notifyListeners());
        conn.db.workPlans.onUpdate(() => notifyListeners());
        conn.db.workPlans.onDelete(() => notifyListeners());
      }

      if (conn.db.workItems) {
        conn.db.workItems.onInsert(() => notifyListeners());
        conn.db.workItems.onUpdate(() => notifyListeners());
        conn.db.workItems.onDelete(() => notifyListeners());
      }

      // Agent tables
      conn.db.agents.onInsert(() => notifyListeners());
      conn.db.agents.onUpdate(() => notifyListeners());
      conn.db.agents.onDelete(() => notifyListeners());

      if (conn.db.agent_channels) {
        conn.db.agent_channels.onInsert(() => notifyListeners());
        conn.db.agent_channels.onUpdate(() => notifyListeners());
        conn.db.agent_channels.onDelete(() => notifyListeners());
      }

      if (conn.db.agent_workspace_mounts) {
        conn.db.agent_workspace_mounts.onInsert(() => notifyListeners());
        conn.db.agent_workspace_mounts.onUpdate(() => notifyListeners());
        conn.db.agent_workspace_mounts.onDelete(() => notifyListeners());
      }

      // Model/provider tables
      if (conn.db.llm_models) {
        conn.db.llm_models.onInsert(() => notifyListeners());
        conn.db.llm_models.onUpdate(() => notifyListeners());
        conn.db.llm_models.onDelete(() => notifyListeners());
      }

      if (conn.db.providers) {
        conn.db.providers.onInsert(() => notifyListeners());
        conn.db.providers.onUpdate(() => notifyListeners());
        conn.db.providers.onDelete(() => notifyListeners());
      }

    } catch (err) {
      connectionPromise = null;
      reject(err);
    }
  });

  return connectionPromise;
}

// ── Data accessors ──

export function getConversations(): Conversation[] {
  if (!db) return [];
  const rows: Conversation[] = [];
  for (const row of db.db.conversations.iter()) {
    rows.push(row as unknown as Conversation);
  }
  rows.sort((a, b) => (b.updatedAt > a.updatedAt ? 1 : b.updatedAt < a.updatedAt ? -1 : 0));
  return rows;
}

export function getConversation(id: string): Conversation | null {
  if (!db) return null;
  const row = db.db.conversations.id.find(id);
  return row ? (row as unknown as Conversation) : null;
}

export function getMessagesForConversation(conversationId: string): ConversationMessage[] {
  if (!db) return [];
  const msgs: ConversationMessage[] = [];
  for (const row of db.db.conversationMessages.iter()) {
    const msg = row as unknown as ConversationMessage;
    if (msg.conversationId === conversationId) {
      msgs.push(msg);
    }
  }
  msgs.sort((a, b) => (a.createdAt > b.createdAt ? 1 : a.createdAt < b.createdAt ? -1 : 0));
  return msgs;
}

export function getWorkPlans(): WorkPlan[] {
  if (!db) return [];
  if (!db.db.workPlans) return [];
  const plans: WorkPlan[] = [];
  for (const row of db.db.workPlans.iter()) {
    plans.push(row as unknown as WorkPlan);
  }
  plans.sort((a, b) => (b.updatedAt > a.updatedAt ? 1 : b.updatedAt < a.updatedAt ? -1 : 0));
  return plans;
}

export function getWorkItems(planId: string): WorkItem[] {
  if (!db) return [];
  if (!db.db.workItems) return [];
  const items: WorkItem[] = [];
  for (const row of db.db.workItems.iter()) {
    const item = row as unknown as WorkItem;
    if (item.planId === planId) {
      items.push(item);
    }
  }
  items.sort((a, b) => a.ordinal - b.ordinal);
  return items;
}

export function getAgentName(agentId: string): string | null {
  if (!db) return null;
  const agent = db.db.agents.id.find(agentId);
  return agent ? (agent as any).displayName : null;
}

export interface AgentRow {
  id: string;
  name: string;
  displayName: string;
  systemPrompt: string;
  model: string;
  utilityModel: string;
  tools: string;
  sandboxImage: string;
  maxIterations: number;
  isActive: boolean;
  isDefault: boolean;
  autoRag?: boolean;
  autoRagLimit?: number;
}

export interface AgentChannelRow {
  id: string;
  agentId: string;
  channel: string;
  sandboxOverride: string;
  enabled: boolean;
}

export interface AgentMountRow {
  id: string;
  agentId: string;
  hostPath: string;
  mountName: string;
  containerPath: string;
  readonly: boolean;
}

export interface LlmModelRow {
  id: string;
  provider: string;
  modelId: string;
  displayName: string;
  contextWindow: number;
  isEnabled: boolean;
}

export interface ProviderRow {
  id: string;
  displayName: string;
  litellmPrefix: string;
  isEnabled: boolean;
}

export function getAgents(): AgentRow[] {
  if (!db) return [];
  const rows: AgentRow[] = [];
  for (const row of db.db.agents.iter()) {
    rows.push(row as unknown as AgentRow);
  }
  rows.sort((a, b) => (a.isDefault ? -1 : b.isDefault ? 1 : a.name.localeCompare(b.name)));
  return rows;
}

export function getAgentChannels(agentId: string): AgentChannelRow[] {
  if (!db || !db.db.agent_channels) return [];
  const rows: AgentChannelRow[] = [];
  for (const row of db.db.agent_channels.iter()) {
    const ch = row as unknown as AgentChannelRow;
    if (ch.agentId === agentId) rows.push(ch);
  }
  return rows;
}

export function getAgentMounts(agentId: string): AgentMountRow[] {
  if (!db || !db.db.agent_workspace_mounts) return [];
  const rows: AgentMountRow[] = [];
  for (const row of db.db.agent_workspace_mounts.iter()) {
    const m = row as unknown as AgentMountRow;
    if (m.agentId === agentId) rows.push(m);
  }
  return rows;
}

export function getLlmModels(): LlmModelRow[] {
  if (!db || !db.db.llm_models) return [];
  const rows: LlmModelRow[] = [];
  for (const row of db.db.llm_models.iter()) {
    const m = row as unknown as LlmModelRow;
    if (m.isEnabled) rows.push(m);
  }
  return rows;
}

export function getProviders(): ProviderRow[] {
  if (!db || !db.db.providers) return [];
  const rows: ProviderRow[] = [];
  for (const row of db.db.providers.iter()) {
    const p = row as unknown as ProviderRow;
    if (p.isEnabled) rows.push(p);
  }
  return rows;
}

export function getAvailableModels(): { id: string; name: string }[] {
  const models = getLlmModels();
  const providers = getProviders();
  const providerMap = new Map(providers.map(p => [p.id, p.litellmPrefix]));
  return models.map(m => ({
    id: `${providerMap.get(m.provider) || m.provider}/${m.modelId}`,
    name: m.displayName,
  }));
}
